import assert from "node:assert/strict";
import { readFile, readdir } from "node:fs/promises";
import { dirname, posix, resolve } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const distributionRoot = resolve(packageRoot, "dist");
const generatedHeader = [
  "// Generated by `pnpm --dir packages/icons run generate:catalogue`.",
  "// Canonical definition modules are the source of truth. Do not edit manually.",
  "",
].join("\n");
function pascalCase(slug) {
  return slug
    .split("-")
    .map((part) => `${part[0]?.toUpperCase()}${part.slice(1)}`)
    .join("");
}

async function collectDefinitionSubpaths(
  directory,
  suffix,
  symbolSuffix = "",
  supportsVariants = false,
) {
  return Object.freeze(
    Object.fromEntries(
      (await readdir(resolve(distributionRoot, directory), {
        recursive: true,
      }))
        .map((entry) => entry.replaceAll("\\", "/"))
        .filter((entry) => entry.endsWith(suffix))
        .map((entry) => {
          const segments = entry.split("/");
          const name = segments.at(-2);
          const stem = segments.at(-1).slice(0, -suffix.length);
          const variant = supportsVariants && stem !== name
            ? stem.slice(`${name}-`.length)
            : undefined;
          const subpath = variant === undefined
            ? name
            : `${name}/${variant}`;

          return [
            subpath,
            `${pascalCase(name)}${
              variant === undefined ? "" : pascalCase(variant)
            }${symbolSuffix}`,
          ];
        })
        .sort(([left], [right]) => left.localeCompare(right)),
    ),
  );
}

function iconDistributionPath(subpath) {
  const [name, variant] = subpath.split("/");
  const filename = variant === undefined
    ? `${name}.icon.js`
    : `${name}-${variant}.icon.js`;

  return `glyphs/${name[0]}/${name}/${filename}`;
}

function collectionDistributionPath(name) {
  return `collections/${name[0]}/${name}/${name}.collection.js`;
}

function moduleSpecifier(fromPath, targetPath) {
  const relation = posix.relative(posix.dirname(fromPath), targetPath);

  return relation.startsWith(".") ? relation : `./${relation}`;
}

const iconSubpaths = await collectDefinitionSubpaths(
  "glyphs",
  ".icon.js",
  "",
  true,
);
const collectionSubpaths = await collectDefinitionSubpaths(
  "collections",
  ".collection.js",
  "Collection",
);

async function collectDistributionFiles(extension) {
  const entries = await readdir(distributionRoot, { recursive: true });

  return entries
    .filter((entry) => entry.endsWith(extension))
    .map((entry) => resolve(distributionRoot, entry))
    .sort((left, right) => left.localeCompare(right));
}

function extractModuleSpecifiers(source) {
  return [...source.matchAll(/\b(?:from|import)\s*(?:\(\s*)?["']([^"']+)["']/gu)]
    .map((match) => match[1])
    .filter((specifier) => specifier !== undefined);
}

test("exposes exact definition families without aggregate roots", async () => {
  const dynamic = await import("@aster/icons/dynamic");

  assert.ok(
    Object.keys(iconSubpaths).length > 0,
    "Expected at least one emitted icon definition subpath.",
  );
  assert.ok(
    Object.keys(collectionSubpaths).length > 0,
    "Expected at least one emitted collection definition subpath.",
  );

  await assert.rejects(
    import("@aster/icons"),
    (error) => error?.code === "ERR_PACKAGE_PATH_NOT_EXPORTED",
  );
  await assert.rejects(
    import("@aster/icons/collections"),
    (error) => error?.code === "ERR_PACKAGE_PATH_NOT_EXPORTED",
  );
  await assert.rejects(readFile(resolve(distributionRoot, "index.js"), "utf8"));
  await assert.rejects(
    readFile(resolve(distributionRoot, "collections/index.js"), "utf8"),
  );

  for (const [subpath, symbol] of Object.entries(iconSubpaths)) {
    const direct = await import(`@aster/icons/${subpath}`);
    const [name, variant] = subpath.split("/");
    const key = `aster/${name}${variant === undefined ? "" : `@${variant}`}`;
    const loader = dynamic.AsterIconLoaders[key];

    assert.ok(loader);
    assert.deepEqual(Object.keys(direct), [symbol]);
    assert.equal(direct[symbol], await loader());
    assert.equal(direct[symbol].identity.name, name);
    assert.equal(direct[symbol].identity.variant, variant);
  }

  for (const [subpath, symbol] of Object.entries(collectionSubpaths)) {
    const direct = await import(`@aster/icons/collections/${subpath}`);
    const loader = dynamic.AsterCollectionLoaders[subpath];

    assert.ok(loader);
    assert.deepEqual(Object.keys(direct), [symbol]);
    assert.equal(direct[symbol], await loader());
    assert.equal(direct[symbol].identity.name, subpath);
    assert.ok(
      direct[symbol].icons.every((definition) =>
        Object.hasOwn(
          dynamic.AsterIconLoaders,
          `${definition.identity.namespace}/${definition.identity.name}`,
        ),
      ),
      `Expected every ${subpath} member to have one exact icon loader.`,
    );
  }
});

test("rejects implementation and undeclared internal subpaths", async () => {
  const [iconSubpath] = Object.keys(iconSubpaths);
  const [collectionSubpath] = Object.keys(collectionSubpaths);
  assert.ok(iconSubpath, "Expected one icon subpath for rejection evidence.");
  assert.ok(
    collectionSubpath,
    "Expected one collection subpath for rejection evidence.",
  );

  await assert.rejects(
    import(`@aster/icons/icons/${iconSubpath}.icon.js`),
    (error) => error?.code === "ERR_MODULE_NOT_FOUND",
  );
  await assert.rejects(
    import(`@aster/icons/collections/${collectionSubpath}.collection.js`),
    (error) => error?.code === "ERR_MODULE_NOT_FOUND",
  );
});

test("publishes only accepted scalable export families", async () => {
  const manifest = JSON.parse(
    await readFile(resolve(packageRoot, "package.json"), "utf8"),
  );
  const expectedExportKeys = [
    ".",
    "./collections",
    "./manifest",
    "./dynamic",
    "./collections/*",
    "./*",
  ];

  assert.deepEqual(Object.keys(manifest.exports), expectedExportKeys);
  assert.equal(manifest.exports["."], null);
  assert.equal(manifest.exports["./collections"], null);
  assert.equal(Object.hasOwn(manifest, "main"), false);
  assert.equal(Object.hasOwn(manifest, "types"), false);
  assert.deepEqual(manifest.exports["./manifest"], {
    types: "./dist/manifest/index.d.ts",
    import: "./dist/manifest/index.js",
  });
  assert.deepEqual(manifest.exports["./dynamic"], {
    types: "./dist/dynamic/index.d.ts",
    import: "./dist/dynamic/index.js",
  });
  assert.deepEqual(manifest.exports["./collections/*"], {
    types: "./dist/generated/facades/collections/*.d.ts",
    import: "./dist/generated/facades/collections/*.js",
  });
  assert.deepEqual(manifest.exports["./*"], {
    types: "./dist/generated/facades/icons/*.d.ts",
    import: "./dist/generated/facades/icons/*.js",
  });
  assert.deepEqual(manifest.dependencies, {
    "@aster/core": "workspace:*",
  });
  assert.equal(manifest.sideEffects, false);
});

test("exposes only metadata through the isolated manifest subpath", async () => {
  const manifest = await import("@aster/icons/manifest");
  const publicSource = await readFile(
    resolve(distributionRoot, "manifest/index.js"),
    "utf8",
  );
  const generatedSource = await readFile(
    resolve(distributionRoot, "generated/manifest/index.js"),
    "utf8",
  );

  assert.deepEqual(Object.keys(manifest).sort(), [
    "AsterCollectionManifest",
    "AsterIconManifest",
  ]);
  assert.deepEqual(extractModuleSpecifiers(publicSource), [
    "../generated/manifest/index.js",
  ]);
  assert.deepEqual(extractModuleSpecifiers(generatedSource), []);
  assert.doesNotMatch(
    generatedSource,
    /\b(?:nodes|viewBox|presentation|Icon\.define|Collection\.define)\b/u,
  );
});

test("exposes exact asynchronous loaders without eager definitions", async () => {
  const dynamic = await import("@aster/icons/dynamic");
  const manifest = await import("@aster/icons/manifest");
  const publicSource = await readFile(
    resolve(distributionRoot, "dynamic/index.js"),
    "utf8",
  );
  const generatedSource = await readFile(
    resolve(distributionRoot, "generated/dynamic/index.js"),
    "utf8",
  );
  const specifiers = extractModuleSpecifiers(generatedSource);

  assert.deepEqual(Object.keys(dynamic).sort(), [
    "AsterCollectionLoaders",
    "AsterIconLoaders",
  ]);
  assert.deepEqual(
    Object.keys(dynamic.AsterIconLoaders),
    manifest.AsterIconManifest.map(({ key }) => key),
  );
  assert.deepEqual(
    Object.keys(dynamic.AsterCollectionLoaders),
    manifest.AsterCollectionManifest.map(({ key }) => key),
  );
  assert.deepEqual(extractModuleSpecifiers(publicSource), [
    "../generated/dynamic/index.js",
  ]);
  assert.ok(specifiers.length > 0);
  assert.ok(
    specifiers.every((specifier) => specifier.startsWith("../facades/")),
  );
  assert.doesNotMatch(generatedSource, /(?:glyphs\/|collections\/[a-z]\/)/u);

  const cameraLoader = dynamic.AsterIconLoaders["aster/camera"];
  const amellusLoader = dynamic.AsterCollectionLoaders.amellus;
  assert.ok(cameraLoader);
  assert.ok(amellusLoader);
  assert.equal((await cameraLoader()).identity.name, "camera");
  assert.equal((await amellusLoader()).identity.name, "amellus");
});

test("keeps every per-icon module isolated from sibling definitions", async () => {
  for (const subpath of Object.keys(iconSubpaths)) {
    const source = await readFile(
      resolve(distributionRoot, iconDistributionPath(subpath)),
      "utf8",
    );
    const specifiers = extractModuleSpecifiers(source);

    assert.deepEqual(specifiers.sort(), [
      "../../../authoring/constants/amellus-icon-authoring-profile.constant.js",
      "../../../authoring/constants/aster-original-icon-authorship.constant.js",
      "@aster/core",
    ]);
    assert.doesNotMatch(source, /(?:icons\/index|manifest|catalogue|registry)/gu);
  }
});

test("routes public definition subpaths through minimal generated facades", async () => {
  for (const [subpath, symbol] of Object.entries(iconSubpaths)) {
    const facadePath = `generated/facades/icons/${subpath}.js`;
    const targetPath = iconDistributionPath(subpath);
    const source = await readFile(
      resolve(distributionRoot, facadePath),
      "utf8",
    );
    const declaration = await readFile(
      resolve(distributionRoot, `generated/facades/icons/${subpath}.d.ts`),
      "utf8",
    );
    const expectedRuntime =
      `${generatedHeader}export { ${symbol} } from "${moduleSpecifier(facadePath, targetPath)}";\n`;
    const expectedDeclaration =
      `export { ${symbol} } from "${moduleSpecifier(facadePath, targetPath)}";\n`;

    assert.equal(source, expectedRuntime);
    assert.equal(declaration, expectedDeclaration);
  }

  for (const [subpath, symbol] of Object.entries(collectionSubpaths)) {
    const facadePath = `generated/facades/collections/${subpath}.js`;
    const targetPath = collectionDistributionPath(subpath);
    const source = await readFile(
      resolve(
        distributionRoot,
        facadePath,
      ),
      "utf8",
    );
    const declaration = await readFile(
      resolve(
        distributionRoot,
        `generated/facades/collections/${subpath}.d.ts`,
      ),
      "utf8",
    );
    const expectedRuntime =
      `${generatedHeader}export { ${symbol} } from "${moduleSpecifier(facadePath, targetPath)}";\n`;
    const expectedDeclaration =
      `export { ${symbol} } from "${moduleSpecifier(facadePath, targetPath)}";\n`;

    assert.equal(source, expectedRuntime);
    assert.equal(declaration, expectedDeclaration);
  }
});

test("keeps every per-collection module isolated from catalogue indexes", async () => {
  for (const subpath of Object.keys(collectionSubpaths)) {
    const source = await readFile(
      resolve(distributionRoot, collectionDistributionPath(subpath)),
      "utf8",
    );
    const specifiers = extractModuleSpecifiers(source);

    assert.equal(specifiers[0], "@aster/core");
    assert.ok(
      specifiers.slice(1).every((specifier) =>
        specifier === "../../../authoring/constants/aster-artwork-licence.constant.js" ||
        /^\.\.\/\.\.\/\.\.\/glyphs\/[a-z]\/([a-z0-9]+(?:-[a-z0-9]+)*)\/\1\.icon\.js$/u.test(specifier),
      ),
      `Expected ${subpath} to import only its artwork licence and declared icon modules.`,
    );
    assert.equal(new Set(specifiers).size, specifiers.length);
    assert.doesNotMatch(
      source,
      /(?:icons\/index|collections\/index|aster-collections|catalogue|registry)/gu,
    );
  }
});

test("emits host-independent side-effect-free ESM", async () => {
  const declarations = await collectDistributionFiles(".d.ts");
  const modules = await collectDistributionFiles(".js");

  assert.ok(declarations.length > 0);
  assert.ok(modules.length > 0);

  for (const declaration of declarations) {
    const source = await readFile(declaration, "utf8");
    const externalSpecifiers = extractModuleSpecifiers(source).filter(
      (specifier) => !specifier.startsWith("."),
    );

    assert.deepEqual(
      [...new Set(externalSpecifiers)],
      externalSpecifiers.length === 0 ? [] : ["@aster/core"],
    );
    assert.doesNotMatch(source, /\/\/\/\s*<reference/iu);
    assert.doesNotMatch(
      source,
      /\b(?:HTMLElement|SVGElement|Document|Window|Buffer|NodeJS)\b/gu,
    );
  }

  for (const module of modules) {
    const source = await readFile(module, "utf8");
    const externalSpecifiers = extractModuleSpecifiers(source).filter(
      (specifier) => !specifier.startsWith("."),
    );

    assert.deepEqual(
      [...new Set(externalSpecifiers)],
      externalSpecifiers.length === 0 ? [] : ["@aster/core"],
    );
    assert.doesNotMatch(source, /\brequire\s*\(/gu);
    assert.doesNotMatch(source, /\bmodule\.exports\b/gu);
    assert.doesNotMatch(
      source,
      /(?:@aster\/core\/|@aster\/build|@aster\/svg|\blilium\b|\blotus\b|\bnode:|\btooling\b)/giu,
    );
  }
});
