import assert from "node:assert/strict";
import {
  mkdir,
  mkdtemp,
  readFile,
  rm,
  unlink,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import test from "node:test";

import { synchroniseIconsCatalogue } from "../../tooling/catalogue/synchronise-icons-catalogue.mjs";

const generatedOutputPaths = Object.freeze({
  iconBarrel: "src/icons/index.ts",
  iconAuthority: "src/icons/constants/aster-icons.constant.ts",
  collectionBarrel: "src/collections/index.ts",
  collectionAuthority:
    "src/collections/constants/aster-collections.constant.ts",
});

const completeGeneratedOutputPaths = Object.freeze(
  Object.values(generatedOutputPaths),
);

function pascalCase(slug) {
  return slug
    .split("-")
    .map((part) => `${part[0].toUpperCase()}${part.slice(1)}`)
    .join("");
}

function iconSource(name, variant) {
  const symbol = `${pascalCase(name)}${
    variant === undefined ? "" : pascalCase(variant)
  }`;
  const variantProperty = variant === undefined ? "" : `, variant: "${variant}"`;

  return [
    `export const ${symbol} = Icon.define({`,
    `  identity: { name: "${name}"${variantProperty} },`,
    "});",
    "",
  ].join("\n");
}

function collectionSource(name, imports = [], members = []) {
  return [
    ...imports,
    ...(imports.length === 0 ? [] : [""]),
    `export const ${pascalCase(name)}Collection = Collection.define({`,
    `  identity: { name: "${name}" },`,
    `  icons: [${members.join(", ")}],`,
    "});\n",
  ].join("\n");
}

async function createPackageFixture() {
  const root = await mkdtemp(join(tmpdir(), "aster-catalogue-source-"));

  await mkdir(resolve(root, "src/icons/constants"), { recursive: true });
  await mkdir(resolve(root, "src/collections/constants"), { recursive: true });
  await writeFile(
    resolve(root, "src/icons/alpha-icon.icon.ts"),
    iconSource("alpha-icon"),
    "utf8",
  );
  await writeFile(
    resolve(root, "src/icons/zeta.icon.ts"),
    iconSource("zeta"),
    "utf8",
  );
  await writeFile(
    resolve(root, "src/collections/sample.collection.ts"),
    collectionSource(
      "sample",
      ['import { AlphaIcon } from "../icons/alpha-icon.icon.js";'],
      ["AlphaIcon"],
    ),
    "utf8",
  );

  return root;
}

async function readGeneratedOutputs(root) {
  return Object.freeze(
    Object.fromEntries(
      await Promise.all(
        completeGeneratedOutputPaths.map(async (path) => [
          path,
          await readFile(resolve(root, path), "utf8"),
        ]),
      ),
    ),
  );
}

test("reports every absent output without writing in check-only mode", async () => {
  const root = await createPackageFixture();

  try {
    const result = await synchroniseIconsCatalogue(root, true);

    assert.deepEqual(result.changedPaths, completeGeneratedOutputPaths);
    assert.equal(result.outputCount, completeGeneratedOutputPaths.length);

    for (const path of completeGeneratedOutputPaths) {
      await assert.rejects(readFile(resolve(root, path), "utf8"));
    }
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("synchronises canonical modules deterministically and reports drift", async () => {
  const root = await createPackageFixture();

  try {
    const generated = await synchroniseIconsCatalogue(root);

    assert.deepEqual(generated.changedPaths, completeGeneratedOutputPaths);
    assert.equal(generated.outputCount, 4);

    const iconBarrelPath = resolve(root, generatedOutputPaths.iconBarrel);
    const iconBarrel = await readFile(iconBarrelPath, "utf8");
    assert.match(iconBarrel, /^\/\/ Generated by/u);
    assert.match(iconBarrel, /Do not edit manually\.\n\nexport/u);
    assert.ok(
      iconBarrel.indexOf("AlphaIcon") < iconBarrel.indexOf("Zeta"),
    );
    assert.match(iconBarrel, /export \{ AsterIcons \}/u);

    const current = await synchroniseIconsCatalogue(root, true);
    assert.deepEqual(current.changedPaths, []);

    await writeFile(iconBarrelPath, "stale\n", "utf8");
    const drift = await synchroniseIconsCatalogue(root, true);
    assert.deepEqual(drift.changedPaths, [generatedOutputPaths.iconBarrel]);
    assert.equal(await readFile(iconBarrelPath, "utf8"), "stale\n");

    await synchroniseIconsCatalogue(root);
    assert.equal(await readFile(iconBarrelPath, "utf8"), iconBarrel);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("adds and removes source modules without manual aggregate edits", async () => {
  const root = await createPackageFixture();

  try {
    await synchroniseIconsCatalogue(root);
    const sourcePath = resolve(root, "src/icons/middle.icon.ts");
    await writeFile(sourcePath, iconSource("middle"), "utf8");

    const added = await synchroniseIconsCatalogue(root);
    assert.deepEqual(added.changedPaths, [
      generatedOutputPaths.iconBarrel,
      generatedOutputPaths.iconAuthority,
    ]);
    assert.match(
      await readFile(resolve(root, generatedOutputPaths.iconBarrel), "utf8"),
      /export \{ Middle \}/u,
    );

    await unlink(sourcePath);
    const removed = await synchroniseIconsCatalogue(root);
    assert.deepEqual(removed.changedPaths, [
      generatedOutputPaths.iconBarrel,
      generatedOutputPaths.iconAuthority,
    ]);
    assert.doesNotMatch(
      await readFile(resolve(root, generatedOutputPaths.iconBarrel), "utf8"),
      /Middle/u,
    );

    const collectionPath = resolve(
      root,
      "src/collections/secondary.collection.ts",
    );
    await writeFile(
      collectionPath,
      collectionSource("secondary"),
      "utf8",
    );
    const collectionAdded = await synchroniseIconsCatalogue(root);
    assert.deepEqual(collectionAdded.changedPaths, [
      generatedOutputPaths.collectionBarrel,
      generatedOutputPaths.collectionAuthority,
    ]);
    assert.match(
      await readFile(
        resolve(root, generatedOutputPaths.collectionBarrel),
        "utf8",
      ),
      /export \{ SecondaryCollection \}/u,
    );

    await unlink(collectionPath);
    const collectionRemoved = await synchroniseIconsCatalogue(root);
    assert.deepEqual(collectionRemoved.changedPaths, [
      generatedOutputPaths.collectionBarrel,
      generatedOutputPaths.collectionAuthority,
    ]);
    assert.doesNotMatch(
      await readFile(
        resolve(root, generatedOutputPaths.collectionBarrel),
        "utf8",
      ),
      /SecondaryCollection/u,
    );
    assert.doesNotMatch(
      await readFile(
        resolve(root, generatedOutputPaths.collectionAuthority),
        "utf8",
      ),
      /SecondaryCollection/u,
    );
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("discovers nested base icons, variants and collections with portable specifiers", async () => {
  const root = await createPackageFixture();

  try {
    const cameraRoot = resolve(root, "src/icons/c/camera");
    const retroRoot = resolve(root, "src/icons/c/camera-retro");
    const archiveRoot = resolve(root, "src/collections/a/archive");
    await mkdir(cameraRoot, { recursive: true });
    await mkdir(retroRoot, { recursive: true });
    await mkdir(archiveRoot, { recursive: true });
    await writeFile(
      resolve(cameraRoot, "camera.icon.ts"),
      iconSource("camera"),
      "utf8",
    );
    await writeFile(
      resolve(cameraRoot, "camera-stippled.icon.ts"),
      iconSource("camera", "stippled"),
      "utf8",
    );
    await writeFile(
      resolve(retroRoot, "camera-retro.icon.ts"),
      iconSource("camera-retro"),
      "utf8",
    );
    await writeFile(
      resolve(archiveRoot, "archive.collection.ts"),
      collectionSource(
        "archive",
        [
          'import { CameraStippled } from "../../../icons/c/camera/camera-stippled.icon.js";',
        ],
        ["CameraStippled"],
      ),
      "utf8",
    );
    await writeFile(
      resolve(root, "src/icons/constants/ignored.icon.ts"),
      "not valid TypeScript",
      "utf8",
    );
    await writeFile(resolve(cameraRoot, "notes.ts"), "ignored\n", "utf8");

    await synchroniseIconsCatalogue(root);

    const iconBarrel = await readFile(
      resolve(root, generatedOutputPaths.iconBarrel),
      "utf8",
    );
    const iconAuthority = await readFile(
      resolve(root, generatedOutputPaths.iconAuthority),
      "utf8",
    );
    const collectionBarrel = await readFile(
      resolve(root, generatedOutputPaths.collectionBarrel),
      "utf8",
    );

    assert.match(
      iconBarrel,
      /export \{ Camera \} from "\.\/c\/camera\/camera\.icon\.js";/u,
    );
    assert.match(
      iconBarrel,
      /export \{ CameraStippled \} from "\.\/c\/camera\/camera-stippled\.icon\.js";/u,
    );
    assert.match(
      iconBarrel,
      /export \{ CameraRetro \} from "\.\/c\/camera-retro\/camera-retro\.icon\.js";/u,
    );
    assert.match(
      iconAuthority,
      /import \{ CameraStippled \} from "\.\.\/c\/camera\/camera-stippled\.icon\.js";/u,
    );
    assert.match(
      collectionBarrel,
      /export \{ ArchiveCollection \} from "\.\/a\/archive\/archive\.collection\.js";/u,
    );
    assert.doesNotMatch(iconBarrel, /ignored|notes/u);

    await unlink(resolve(retroRoot, "camera-retro.icon.ts"));
    const removed = await synchroniseIconsCatalogue(root);

    assert.deepEqual(removed.changedPaths, [
      generatedOutputPaths.iconBarrel,
      generatedOutputPaths.iconAuthority,
    ]);
    assert.doesNotMatch(
      await readFile(resolve(root, generatedOutputPaths.iconBarrel), "utf8"),
      /CameraRetro/u,
    );
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("rejects removed icons retained by canonical collections before writing", async () => {
  const root = await createPackageFixture();

  try {
    await synchroniseIconsCatalogue(root);
    const outputs = await readGeneratedOutputs(root);
    await unlink(resolve(root, "src/icons/alpha-icon.icon.ts"));

    await assert.rejects(
      synchroniseIconsCatalogue(root),
      /contains dangling icon reference/u,
    );
    assert.deepEqual(await readGeneratedOutputs(root), outputs);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("rejects invalid, malformed and ambiguous canonical modules before writing", async () => {
  const cases = [
    {
      files: [["Bad.icon.ts", iconSource("bad")]],
      pattern: /Invalid canonical catalogue source name/u,
    },
    {
      files: [["wrong.icon.ts", "export const Other = Icon.define({});\n"]],
      pattern: /must export exactly one constant named Wrong/u,
    },
    {
      files: [["plain.icon.ts", "export const Plain = {};\n"]],
      pattern: /must initialise Icon\.define/u,
    },
    {
      files: [["broken.icon.ts", "export const Broken = {;\n"]],
      pattern: /Invalid TypeScript catalogue source/u,
    },
    {
      files: [
        ["foo-1.icon.ts", iconSource("foo-1")],
        ["foo1.icon.ts", iconSource("foo1")],
      ],
      pattern: /Ambiguous canonical catalogue source symbol/u,
    },
    {
      files: [["aster-icons.icon.ts", iconSource("aster-icons")]],
      pattern: /Ambiguous canonical catalogue source symbol/u,
    },
    {
      files: [[
        "c/camera/camera.icon.ts",
        'export const Camera = Icon.define({ identity: { name: "photograph" } });\n',
      ]],
      pattern: /identity must match camera/u,
    },
    {
      files: [[
        "c/camera/camera-filled.icon.ts",
        'export const CameraFilled = Icon.define({ identity: { name: "camera", variant: "outline" } });\n',
      ]],
      pattern: /identity must match camera@filled/u,
    },
    {
      files: [["x/camera/camera.icon.ts", iconSource("camera")]],
      pattern: /Invalid canonical catalogue source initial directory/u,
    },
    {
      files: [
        ["c/camera/camera-retro.icon.ts", iconSource("camera", "retro")],
        ["c/camera-retro/camera-retro.icon.ts", iconSource("camera-retro")],
      ],
      pattern: /Ambiguous canonical catalogue source symbol: CameraRetro/u,
    },
    {
      files: [["a/alpha-icon/alpha-icon.icon.ts", iconSource("alpha-icon")]],
      pattern: /Duplicate canonical catalogue source identity: alpha-icon/u,
    },
  ];

  for (const fixture of cases) {
    const root = await createPackageFixture();

    try {
      for (const [name, content] of fixture.files) {
        const sourcePath = resolve(root, "src/icons", name);
        await mkdir(dirname(sourcePath), { recursive: true });
        await writeFile(sourcePath, content, "utf8");
      }

      await assert.rejects(
        synchroniseIconsCatalogue(root),
        fixture.pattern,
      );

      for (const path of completeGeneratedOutputPaths) {
        await assert.rejects(readFile(resolve(root, path), "utf8"));
      }
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  }
});
