import assert from "node:assert/strict";
import { mkdir, mkdtemp, readFile, rm, unlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import test from "node:test";

import { synchroniseIconsCatalogue } from "../../tooling/catalogue/synchronise-icons-catalogue.mjs";

async function createPackageFixture() {
  const root = await mkdtemp(join(tmpdir(), "aster-catalogue-source-"));

  await mkdir(resolve(root, "src/icons/constants"), { recursive: true });
  await mkdir(resolve(root, "src/collections/constants"), { recursive: true });
  await writeFile(
    resolve(root, "src/icons/alpha-icon.icon.ts"),
    "export const AlphaIcon = {};\n",
    "utf8",
  );
  await writeFile(
    resolve(root, "src/icons/zeta.icon.ts"),
    "export const Zeta = {};\n",
    "utf8",
  );
  await writeFile(
    resolve(root, "src/collections/aster.collection.ts"),
    "export const AsterCollection = {};\n",
    "utf8",
  );

  return root;
}

test("synchronises canonical modules deterministically and reports drift", async () => {
  const root = await createPackageFixture();

  try {
    const generated = await synchroniseIconsCatalogue(root);

    assert.deepEqual(generated.changedPaths, [
      "src/icons/index.ts",
      "src/icons/constants/aster-icons.constant.ts",
      "src/collections/index.ts",
      "src/collections/constants/aster-collections.constant.ts",
    ]);
    assert.equal(generated.outputCount, 4);

    const iconBarrelPath = resolve(root, "src/icons/index.ts");
    const iconBarrel = await readFile(iconBarrelPath, "utf8");
    assert.match(iconBarrel, /^\/\/ Generated by/u);
    assert.match(iconBarrel, /Do not edit manually\.\n\nexport/u);
    assert.ok(
      iconBarrel.indexOf("AlphaIcon") < iconBarrel.indexOf("Zeta"),
    );
    assert.match(iconBarrel, /export \{ AsterIcons \}/u);

    const current = await synchroniseIconsCatalogue(root, true);
    assert.deepEqual(current.changedPaths, []);

    await writeFile(iconBarrelPath, "stale\n", "utf8");
    const drift = await synchroniseIconsCatalogue(root, true);
    assert.deepEqual(drift.changedPaths, ["src/icons/index.ts"]);
    assert.equal(await readFile(iconBarrelPath, "utf8"), "stale\n");

    await synchroniseIconsCatalogue(root);
    assert.equal(await readFile(iconBarrelPath, "utf8"), iconBarrel);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("adds and removes source modules without manual aggregate edits", async () => {
  const root = await createPackageFixture();

  try {
    await synchroniseIconsCatalogue(root);
    const sourcePath = resolve(root, "src/icons/middle.icon.ts");
    await writeFile(sourcePath, "export const Middle = {};\n", "utf8");

    const added = await synchroniseIconsCatalogue(root);
    assert.deepEqual(added.changedPaths, [
      "src/icons/index.ts",
      "src/icons/constants/aster-icons.constant.ts",
    ]);
    assert.match(
      await readFile(resolve(root, "src/icons/index.ts"), "utf8"),
      /export \{ Middle \}/u,
    );

    await unlink(sourcePath);
    const removed = await synchroniseIconsCatalogue(root);
    assert.deepEqual(removed.changedPaths, [
      "src/icons/index.ts",
      "src/icons/constants/aster-icons.constant.ts",
    ]);
    assert.doesNotMatch(
      await readFile(resolve(root, "src/icons/index.ts"), "utf8"),
      /Middle/u,
    );

    const collectionPath = resolve(
      root,
      "src/collections/secondary.collection.ts",
    );
    await writeFile(
      collectionPath,
      "export const SecondaryCollection = {};\n",
      "utf8",
    );
    const collectionAdded = await synchroniseIconsCatalogue(root);
    assert.deepEqual(collectionAdded.changedPaths, [
      "src/collections/index.ts",
      "src/collections/constants/aster-collections.constant.ts",
    ]);
    assert.match(
      await readFile(resolve(root, "src/collections/index.ts"), "utf8"),
      /export \{ SecondaryCollection \}/u,
    );

    await unlink(collectionPath);
    const collectionRemoved = await synchroniseIconsCatalogue(root);
    assert.deepEqual(collectionRemoved.changedPaths, [
      "src/collections/index.ts",
      "src/collections/constants/aster-collections.constant.ts",
    ]);
    assert.doesNotMatch(
      await readFile(resolve(root, "src/collections/index.ts"), "utf8"),
      /SecondaryCollection/u,
    );
    assert.doesNotMatch(
      await readFile(
        resolve(root, "src/collections/constants/aster-collections.constant.ts"),
        "utf8",
      ),
      /SecondaryCollection/u,
    );
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("rejects invalid, malformed and ambiguous canonical modules before writing", async () => {
  const cases = [
    {
      files: [["Bad.icon.ts", "export const Bad = {};\n"]],
      pattern: /Invalid canonical catalogue source filename/u,
    },
    {
      files: [["wrong.icon.ts", "export const Other = {};\n"]],
      pattern: /must export exactly one constant named Wrong/u,
    },
    {
      files: [["broken.icon.ts", "export const Broken = {;\n"]],
      pattern: /Invalid TypeScript catalogue source/u,
    },
    {
      files: [
        ["foo-1.icon.ts", "export const Foo1 = {};\n"],
        ["foo1.icon.ts", "export const Foo1 = {};\n"],
      ],
      pattern: /Ambiguous canonical catalogue source symbol/u,
    },
    {
      files: [["aster-icons.icon.ts", "export const AsterIcons = {};\n"]],
      pattern: /Ambiguous canonical catalogue source symbol/u,
    },
  ];

  for (const fixture of cases) {
    const root = await createPackageFixture();

    try {
      for (const [name, content] of fixture.files) {
        await writeFile(resolve(root, "src/icons", name), content, "utf8");
      }

      await assert.rejects(
        synchroniseIconsCatalogue(root),
        fixture.pattern,
      );
      await assert.rejects(readFile(resolve(root, "src/icons/index.ts")));
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  }
});
