// Generated by `pnpm --dir packages/icons run generate:catalogue`.
// Canonical definition modules are the source of truth. Do not edit manually.

import type { CollectionDefinition } from "@aster/core";
import { AmellusCollection } from "../amellus.collection.js";
import { AsterCollection } from "../aster.collection.js";

/**
 * @description Complete immutable index of canonical Aster collection definitions.
 * @remarks Icon discovery remains independent from collection membership and collection count.
 */
export const AsterCollections: readonly CollectionDefinition[] = Object.freeze([
  AmellusCollection,
  AsterCollection,
]);
