import assert from "node:assert/strict";
import {
  mkdir,
  mkdtemp,
  readFile,
  rm,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import { AsterCollection } from "@aster/icons";
import { PilotReviewHost } from "../../tooling/review/runtime/pilot-review.host.js";
import { PilotReviewPlanner } from "../../tooling/review/runtime/pilot-review.planner.js";

test("plans deterministic disposable pilot review evidence", () => {
  const planner = new PilotReviewPlanner();
  const first = planner.plan(AsterCollection);
  const second = planner.plan(AsterCollection);

  assert.deepEqual(first, second);
  assert.ok(Object.isFrozen(first));
  assert.equal(first.length, 23);
  assert.deepEqual(
    first.map((file) => file.path),
    [
      "report.json",
      "contact-sheets/default-light.svg",
      "contact-sheets/default-dark.svg",
      "contact-sheets/minimum-light.svg",
      "contact-sheets/minimum-dark.svg",
      "contact-sheets/silhouette-comparison.svg",
      "contact-sheets/reference-comparison.svg",
      ...AsterCollection.icons.map(
        (definition) => `icons/${definition.identity.name}.svg`,
      ),
    ],
  );

  for (const file of first.slice(1)) {
    assert.match(file.content, /^<!-- Generated by pnpm review:pilot/u);
    assert.ok(Object.isFrozen(file));
  }
});

test("reports technical evidence without claiming aesthetic authority", () => {
  const reportFile = new PilotReviewPlanner()
    .plan(AsterCollection)
    .find((file) => file.path === "report.json");

  assert.ok(reportFile !== undefined);

  const report = JSON.parse(reportFile.content) as {
    summary: {
      iconCount: number;
      blockingFindings: number;
      minimumPrimitives: number;
      maximumPrimitives: number;
    };
    icons: readonly {
      anchors: { offGrid: number };
      strokeConsistent: boolean;
    }[];
    limitations: readonly string[];
  };

  assert.deepEqual(report.summary, {
    iconCount: 16,
    blockingFindings: 0,
    advisoryFindings: 0,
    minimumPrimitives: 1,
    maximumPrimitives: 10,
  });
  assert.equal(report.icons.length, 16);
  assert.ok(report.icons.every((icon) => icon.anchors.offGrid === 0));
  assert.ok(report.icons.every((icon) => icon.strokeConsistent));
  assert.ok(
    report.limitations.some((limitation) =>
      limitation.includes("never assign aesthetic quality"),
    ),
  );
});

test("replaces only the fixed owned review output boundary", async () => {
  const workspaceRoot = await mkdtemp(join(tmpdir(), "aster-review-"));
  const reviewRoot = join(workspaceRoot, "dist", "review");
  const outputRoot = join(reviewRoot, "aster");
  const sentinel = join(reviewRoot, "sentinel.txt");

  try {
    await mkdir(outputRoot, { recursive: true });
    await writeFile(join(outputRoot, "stale.txt"), "stale", "utf8");
    await writeFile(sentinel, "retained", "utf8");

    await new PilotReviewHost().generate(workspaceRoot);

    assert.equal(await readFile(sentinel, "utf8"), "retained");
    await assert.rejects(readFile(join(outputRoot, "stale.txt"), "utf8"));

    const report = JSON.parse(
      await readFile(join(outputRoot, "report.json"), "utf8"),
    ) as { summary: { iconCount: number } };

    assert.equal(report.summary.iconCount, 16);
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true });
  }
});
