// Generated by `pnpm --dir packages/icons run generate:catalogue`.
// Canonical definition modules are the source of truth. Do not edit manually.

export { AsterCollection } from "./aster.collection.js";
export { AsterCollections } from "./constants/aster-collections.constant.js";
