/**
 * @description Immutable namespace-free names used by the accepted and explicitly rejected SVG subset.
 */
export const svgSourceAttributeNames = Object.freeze({
  viewBox: "viewBox",
  namespaceDeclaration: "xmlns",
  version: "version",
  identifier: "id",
  enableBackground: "enable-background",
  space: "space",
  pathData: "d",
  centreX: "cx",
  centreY: "cy",
  radius: "r",
  radiusX: "rx",
  radiusY: "ry",
  x: "x",
  y: "y",
  width: "width",
  height: "height",
  x1: "x1",
  y1: "y1",
  x2: "x2",
  y2: "y2",
  points: "points",
  fill: "fill",
  fillRule: "fill-rule",
  stroke: "stroke",
  strokeWidth: "stroke-width",
  strokeLineCap: "stroke-linecap",
  strokeLineJoin: "stroke-linejoin",
  strokeMiterLimit: "stroke-miterlimit",
  opacity: "opacity",
  fillOpacity: "fill-opacity",
  strokeOpacity: "stroke-opacity",
  transform: "transform",
  href: "href",
  source: "src",
} as const);
