// Generated by `pnpm --dir packages/icons run generate:catalogue`.
// Canonical definition modules are the source of truth. Do not edit manually.

export { ArrowDown } from "./arrow-down.icon.js";
export { ArrowLeft } from "./arrow-left.icon.js";
export { ArrowRight } from "./arrow-right.icon.js";
export { ArrowUp } from "./arrow-up.icon.js";
export { Check } from "./check.icon.js";
export { Close } from "./close.icon.js";
export { Download } from "./download.icon.js";
export { Info } from "./info.icon.js";
export { Mail } from "./mail.icon.js";
export { Menu } from "./menu.icon.js";
export { Pause } from "./pause.icon.js";
export { Play } from "./play.icon.js";
export { Plus } from "./plus.icon.js";
export { Search } from "./search.icon.js";
export { Settings } from "./settings.icon.js";
export { Star } from "./star.icon.js";
export { Warning } from "./warning.icon.js";
export { AsterIcons } from "./constants/aster-icons.constant.js";
